# Section 9: Working with Common Python Libraries
This section will provide an overview of (internally) commonly-used packages: NumPy, pandas and Matplotlib.
Part 3 will be run over the next few weeks. This week will cover NumPy only.

## 1 - Why we use packages
One of the most significant benefits of Python over other programming language is its broad range of open-source packages. Although Python comes well equipped with a lot of in-built functionality and building blocks to create useful code, packages provide us with ready-made tools that save us a lot of time. Packages are essentially collections of prewritten code that make Python much more useable. Instead of writing all functions from scratch to import, handle and visualise data, we can use packages such as pandas, NumPy and Matplotlib respectively, which are well-tested and standardised with helpful documentation available. By using packages such as these, we can vastly reduce the amount of code we need to write, speed up our processes, and make our code more reusable.

## 2 - Importing and using pre-installed packages
There are several ways to import a package for use. We are going to begin with the example package NumPy. This package is incredibly useful for carrying out mathematical functions in Python, and contains useful data structures that we will use regularly in this course. These functionalities will be covered in Section 3. To access the functionalities, we need to import the module. The most simple way to do this is to type import and then the name of the package as below.

In [1]:
import numpy

We can then access and use methods and attributes of this package by prefacing them with the name of the package followed by a full stop. For example the code below runs the method sqrt() which takes the square root of a given number.

In [2]:
numpy.sqrt(4)

2.0

Sometimes, we may not wish to type the full name of the package every time. Typically, we abbreviate it to 2 or 3 letters, in the case of numpy we generally use np. To import a package under a specific name we type import package as name, as below.

In [3]:
import numpy as np

We may now access and use methods and attributes through its abbreviated name.

In [4]:
np.sqrt(9)

3.0

In some cases, where we are only interested in one method of a package we can import that specifically using the syntax from package import method.

In [5]:
from numpy import sqrt

Now we can simply use the name of the method without specifying the package.

In [6]:
sqrt(16)

4.0

We can import multiple features by typing them out in a comma separated list.

In [7]:
from numpy import sqrt, round

In [8]:
round(0.23454, 2)

0.23

This method can also be used to import *all* methods from a package in this way by replacing method with * to represent all.

In [9]:
from numpy import *

Not only has sqrt been imported, but additional methods and attributes. Below we can see the example attribute numpy.e, Euler's constant.

In [10]:
e

2.718281828459045

We can also combine the syntax of 'from' and 'as' and type from package import method as name to import a method from a package to have a specific name to later reference.

In [11]:
from numpy import sqrt as SQRT

In [12]:
SQRT(25)

5.0

However, there is a big drawback with importing individual methods, and with naming them. Without the preface of the package this name may well have the same name as a built-in Python method. This can then overwrite that method and block functionality. The table below summarises these import methods and their advantages and disadvantages. Following this section we will study some example packages, and recommend the appropriate method for importing.


|Method|Syntax|Pros|Cons|
|---------|-----------|------|-----|
|1|import package|Simplest method|Can be inefficient to install all methods, retyping long name can reduce readability/reusability|
|2|import package as name|Packages that will be used often, and have multiple methods that will be used|Can be inefficient to install all methods|
|3|from package import method|Very efficient when only one or a few methods/attributes are required|Name may be not be ideal for reusability/readability|
|4|from package import method as name|Very efficient when only one or a few methods/attributes are required, short name more reusable/understandable|Must be careful not to overwrite existing function with name|
|5|from package import *|Least code to write|Inefficient to install all elements, names may overwrite in-built methods|

## 3 - Common Packages

### 3.1 - Numpy
We've already started looking at numpy but let's look deeper into some of the attributes and methods within this very handy package.

#### 3.1.1 - Numpy constants

np.e
np.pi
np.inf
np.nan

#### 3.1.2 NumPy rounding

In [13]:
x = np.pi

print(f'Floor: {np.floor(x)}')
print(f'Ceiling: {np.ceil(x)}')
print(f'Round: {np.round(x,5)}')

Floor: 3.0
Ceiling: 4.0
Round: 3.14159


#### 3.1.4 NumPy Mathematical Functions
NumPy contains a number of simple mathematical functions similar to those already available with Python.

In [14]:
np.add(2,6) # 2+6
np.subtract(3,4) # 3-4
np.power(3,2) # 3 raised to the power of 2 (3^2)
np.sqrt(36) # square root of 6

6.0

#### Exercise 3.1.4
How would we carry out the 4 above operations without using the NumPy package?

Numpy also gives the ability to carry out some new functionality.

In [15]:
np.exp(2) # e^2
np.log(np.e) # Natural log of e (log(e))
np.sin(20) # sine of 20
np.cos(30) # cosine of 30
np.tan(40) # tangent of 40
np.radians(15) # converts 15 degrees to radians

0.2617993877991494

#### 3.1.5 NumPy arrays

NumPy also has it's own N-dimensional, array-type, built-in data structures - NumPy Arrays. These are a collection of “items” of the same type, indexed by N integers.

All ndarrays ar*e homogeneo*, this means thats: ever"y it"em takes up the samamountck of memory, andre interpreted in the same way. However, the items within the array will be interpreted differently depending on the object data type (which must be consistent through the array).y. In addition to basic typesuch as integers and floats.), the data type objects can also represent data structures.

An item extracted from an array, e.g., by indexing, is represented by a Python object whose type is one of the array scalar types built in NumPy. The array scalars allow easy manipulation of also more complicated arrangem.

An array is created using numpy.array([comma separated list]).
Each layer of square brackets denotes a new dimension. For example, below has only 1 diion.ata.

In [16]:
x_1d = np.array([1,2,3])

This means when we index this, to extract data, we only need to use one integer. Remember in Python we index from 0, so to access the first element we use array[0].

In [17]:
x_1d[0]

1

#### Exercise 3.1.5.1
Use your knowledge from the first Python tutorial to print out:
- the second and third elements together
- all elements

Similarly, we can create a 2 dimensional array by adding a second layer of square brackets.

In [18]:
x_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [19]:
x_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

We may then access an entire row of this array with a single integer index, or access a specific value by specifying both the row and column (comma-separated).

In [20]:
x_2d[0]

array([1, 2, 3])

In [21]:
x_2d[0,1]

2

We may continue this with as many dimensions/layers as we would like.

In [22]:
x_3d = np.array([[[1,2],[2,7],[3,6]], [[4,6],[5,2],[6,1]]])

#### Exercise 3.1.5.2
Use your knowledge of indices to access the number 4 in this array.

##### Summarising attributes and methods

Often we may create many arrays, or have some precreated. In these instances it is useful to check or recall what dimensions they have. We do this using the ndim attribute,

In [46]:
x_3d.ndim

3

For full details on the shape we can use the shape attribute,

In [23]:
x_3d.shape

(2, 3, 2)

We can see that this is 3-dimensional, with 2 rows, 3 columns and 2 'stacks'.

Alternatively, if we only wish to know the size in terms of number of elements we can use the size attribute,

In [48]:
x_3d.size

12

Importantly, we can change the dimensionality and shape of the array whilst maintaining the size. This will be covered later in the course at it is a very important method for preparing data for Machine Learning Pipelines.

As well as describing the architecture of the array, we can access summary statistics using in-built methods.

In [73]:
x_3d.sum() # Adds all elements in the array together to produce a sum total

42

In [69]:
x_3d.max() # Returns the maximum value in the array

6

In [70]:
x_3d.mean() # Returns the mean value in the array

3.5

In [71]:
x_3d.min() # Returns the minimum value in the array

1

##### Special NumPy arrays
NumPy allows us to create some arrays without populating all rows, columns etc. ourselves. The most common examples are numpy.zeros, creating an array of zeros, and numpy.ones creating an array of ones.

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

We can also make these in higher dimensional spaces, specifying dimsensions within brackets.

In [36]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

NumPy is also able to create arrays running through a range of values using numpy.arange().

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Exercise 3.1.5.3
Recreate the range given in the above array using the Python range() function.

The syntax works almost identically to the inbuild Python range() function where at simplest we specify just an end value as above, and the default loops from 0 to this value in steps of 1. Similarly, we can add an optional starting value, and define iteration spacing. However, the key difference is that the iteration spacing is defined by the iterative increase rather than the number of values that should be generated. Similarly, we may now specify non-integer values for the start, end or spacing.

In [57]:
np.arange(4.25,16,0.75)

array([ 4.25,  5.  ,  5.75,  6.5 ,  7.25,  8.  ,  8.75,  9.5 , 10.25,
       11.  , 11.75, 12.5 , 13.25, 14.  , 14.75, 15.5 ])

#### Exercise 3.15.4
Create a NumPy array between 5.5 and 8.5 increasing in increments of 0.25.

Randomised data may also be produced using a sub-module of NumPy called random. A random array may be generated of numbers between 0 and 1 using the method rand(), with the size of the array specified within the brackets.

In [91]:
r = np.random.rand(10)

In [92]:
r = np.random.rand(2,3,2)

##### Exercise 3.15.5

Create a random array with 3 rows and 4 columns.
Multiply all elements in this array by 100.

##### Adding, removing and sorting

An array may be sorted in numerical order using the sort() method. This is both an implicit method of an array which can be used to sort the array without returning anything, as below:

In [63]:
x = np.array([2,1,2,3,4,5,2,1])
x.sort()
x

array([1, 1, 2, 2, 2, 3, 4, 5])

or by using the in-built NumPy method which returns the sorted array.

In [64]:
np.sort(x)

array([1, 1, 2, 2, 2, 3, 4, 5])

View more sorting methods [here](https://numpy.org/devdocs/reference/routines.sort.html).

Once sorted, an array may be flipped to produce reverse-ordered data.

In [77]:
np.flip(x)

array([5, 4, 3, 2, 2, 2, 1, 1])

Arrays can be combined using the concatenate() method, as long as their dimensions are suitable. The arrays to be combined must be given in a list.

In [65]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8])

np.concatenate([a,b,c])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
a = np.array([[1,2], [3,4], [5,6]])
b = np.array([[7,8], [9,10]])

np.concatenate([a,b])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

For more information on NumPy functionality view the [docs](https://numpy.org/doc/stable/user/absolute_beginners.html) or DataCamp's [cheatsheet](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://media.datacamp.com/legacy/image/upload/v1676302459/Marketing/Blog/Numpy_Cheat_Sheet.pdf).
